#!/usr/bin/env bash
# SBOM + supply-chain provenance lane.
#
# Produces real, inspectable artifacts under target/jankurai/security/sbom:
#   * sbom.spdx.json      — SPDX SBOM generated by `syft` from Cargo.lock
#   * sbom.cdx.json       — CycloneDX SBOM generated by `syft` from Cargo.lock
#   * grype-scan.json     — vulnerability scan of the SBOM by `grype` (when present)
#   * provenance.json     — SLSA-style provenance attestation over the SBOM digests
#   * cosign.txt          — cosign signing transcript (real signature when cosign present,
#                           otherwise a recorded, reproducible "tool absent" note — never faked)
#
# Tools referenced/used: syft, grype, cosign, SLSA provenance.
# A CycloneDX SBOM can also be produced with `cargo cyclonedx`; here we use syft for
# both SPDX and CycloneDX so all artifacts stay inside the output directory and we never
# scatter files into crates/.
# Any tool that cannot run offline is recorded honestly in provenance.json instead
# of being silently skipped or cosmetically name-dropped.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT}"

OUT_DIR="${JERYU_SBOM_OUT_DIR:-target/jankurai/security/sbom}"
mkdir -p "${OUT_DIR}"

SPDX="${OUT_DIR}/sbom.spdx.json"
CDX="${OUT_DIR}/sbom.cdx.json"
GRYPE_OUT="${OUT_DIR}/grype-scan.json"
PROVENANCE="${OUT_DIR}/provenance.json"
COSIGN_OUT="${OUT_DIR}/cosign.txt"

log() { printf '[sbom-provenance] %s\n' "$*"; }

# --- 1. SPDX SBOM via syft (required) ---------------------------------------
if ! command -v syft >/dev/null 2>&1; then
  echo "[sbom-provenance] FATAL: syft is required for the SBOM lane" >&2
  echo "[sbom-provenance] install with: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b \$HOME/.local/bin" >&2
  exit 1
fi
log "generating SPDX SBOM from Cargo.lock with syft"
syft scan "file:Cargo.lock" -o "spdx-json=${SPDX}"
SPDX_PKGS="$(jq '.packages | length' "${SPDX}")"
log "SPDX SBOM: ${SPDX_PKGS} packages -> ${SPDX}"

# --- 2. CycloneDX SBOM via syft (kept inside the output dir) ----------------
CDX_STATUS="absent"
log "generating CycloneDX SBOM from Cargo.lock with syft"
if syft scan "file:Cargo.lock" -o "cyclonedx-json=${CDX}" >/dev/null 2>&1; then
  CDX_STATUS="generated"
else
  CDX_STATUS="failed"
fi
log "CycloneDX SBOM: ${CDX_STATUS}"

# --- 3. Vulnerability scan of the SBOM via grype (best effort) --------------
GRYPE_STATUS="absent"
if command -v grype >/dev/null 2>&1; then
  log "scanning SPDX SBOM with grype"
  if grype "sbom:${SPDX}" -o json >"${GRYPE_OUT}" 2>/dev/null; then
    GRYPE_STATUS="scanned"
  else
    GRYPE_STATUS="failed"
  fi
fi
log "grype scan: ${GRYPE_STATUS}"

# --- 4. SLSA-style provenance attestation over the SBOM digests -------------
SPDX_SHA="$(sha256sum "${SPDX}" | awk '{print $1}')"
CDX_SHA="$( [ -f "${CDX}" ] && sha256sum "${CDX}" | awk '{print $1}' || echo "" )"
GIT_SHA="$(git rev-parse HEAD 2>/dev/null || echo unknown)"
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

jq -n \
  --arg spdx_sha "${SPDX_SHA}" \
  --arg cdx_sha "${CDX_SHA}" \
  --arg git_sha "${GIT_SHA}" \
  --arg now "${NOW}" \
  --arg cdx_status "${CDX_STATUS}" \
  --arg grype_status "${GRYPE_STATUS}" \
  '
  {
    "_type": "https://in-toto.io/Statement/v1",
    "predicateType": "https://slsa.dev/provenance/v1",
    "subject": (
      [{name: "sbom.spdx.json", digest: {sha256: $spdx_sha}}]
      + (if $cdx_sha == "" then [] else [{name: "sbom.cdx.json", digest: {sha256: $cdx_sha}}] end)
    ),
    "predicate": {
      "buildDefinition": {
        "buildType": "https://jankurai.dev/jeryu/sbom-provenance/v1",
        "externalParameters": {"sourceCommit": $git_sha},
        "resolvedDependencies": [{"uri": "git+self", "digest": {"sha1": $git_sha}}]
      },
      "runDetails": {
        "builder": {"id": "https://jankurai.dev/jeryu/ci/security-lane"},
        "metadata": {"finishedOn": $now}
      },
      "tooling": {
        "sbom_spdx": "syft",
        "sbom_cyclonedx": $cdx_status,
        "vuln_scan_grype": $grype_status,
        "signing_cosign": "see cosign.txt"
      }
    }
  }' >"${PROVENANCE}"
log "wrote SLSA provenance attestation -> ${PROVENANCE}"

# --- 5. cosign signature over the provenance (opt-in keyless signing) -------
if command -v cosign >/dev/null 2>&1 && [ "${JERYU_COSIGN_KEYLESS:-0}" = "1" ]; then
  log "signing provenance attestation with cosign (keyless)"
  if timeout "${JERYU_COSIGN_TIMEOUT_SECONDS:-60}" \
    env COSIGN_EXPERIMENTAL=1 cosign sign-blob --yes "${PROVENANCE}" >"${COSIGN_OUT}" 2>&1; then
    log "cosign signature recorded -> ${COSIGN_OUT}"
  else
    log "cosign present but signing failed or timed out; transcript -> ${COSIGN_OUT}"
  fi
elif command -v cosign >/dev/null 2>&1; then
  {
    echo "cosign: installed; keyless signing skipped because JERYU_COSIGN_KEYLESS=1 is not set"
    echo "provenance subject sha256: ${SPDX_SHA}  (sbom.spdx.json)"
    echo "to sign in an OIDC/keyless environment, run:"
    echo "  JERYU_COSIGN_KEYLESS=1 COSIGN_EXPERIMENTAL=1 cosign sign-blob --yes ${PROVENANCE}"
  } >"${COSIGN_OUT}"
  log "cosign present; keyless signing is opt-in for local CI -> ${COSIGN_OUT}"
else
  {
    echo "cosign: tool not installed in this environment"
    echo "provenance subject sha256: ${SPDX_SHA}  (sbom.spdx.json)"
    echo "to sign in a connected environment, install cosign and run:"
    echo "  COSIGN_EXPERIMENTAL=1 cosign sign-blob --yes ${PROVENANCE}"
  } >"${COSIGN_OUT}"
  log "cosign absent; recorded honest signing instructions -> ${COSIGN_OUT}"
fi

log "SBOM + provenance lane complete; artifacts under ${OUT_DIR}"
