#!/usr/bin/env bash
set -euo pipefail
out="PHASE11_MANIFEST.txt"
{
  echo "Jeryu repository manifest"
  echo "Generated by scripts/write-manifest.sh"
  echo
  find . -type f \
    ! -path './.git/*' \
    ! -path './target/*' \
    ! -name '._*' \
    ! -name 'PHASE11_MANIFEST.txt' \
    | sed 's#^./##' \
    | sort
} > "$out"
cat "$out"
