#!/usr/bin/env bash
# Generate per-release production env material for an atomicsoul deploy.
#
# Output is intentionally written outside the checkout by default so production
# secrets are never committed. Each invocation creates fresh runtime and signing
# keys.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT}"

release="${JERYU_RELEASE_TAG:-}"
out_dir=""
force=0
domain="${JERYU_PRODUCTION_DOMAIN:-git.neverhuman.org}"
host="${JERYU_ATOMICSOUL_HOST:-atomicsoul}"
bind="${JERYU_SERVE_BIND:-127.0.0.1:8787}"
data_dir="${JERYU_DATA_DIR:-/home/ubuntu/.local/share/jeryu}"
spa_dir="${JERYU_SPA_DIR:-/home/ubuntu/.jeryu/share/web-dist}"
split_manifest="${JERYU_SPLIT_MANIFEST:-/home/ubuntu/.jeryu/share/repos.manifest.toml}"
release_root="${JERYU_ATOMICSOUL_RELEASE_ROOT:-/home/ubuntu/.jeryu/releases}"

usage() {
  cat <<'USAGE'
usage: make-production-env.sh [--release RELEASE] [--out-dir DIR] [--force]
                              [--domain HOSTNAME] [--host SSH_HOST]

Generates:
  production.env          secret sourceable env for local release/deploy commands
  signing-key.pem         per-release Ed25519 private key for SHA256SUMS signing
  signing-key.pub.pem     public verifier key pushed with deploy evidence
  PUBLIC.env              nonsecret release/deploy metadata

Defaults:
  --release: prod-<UTC timestamp>-<current git sha prefix>
  --out-dir: ~/.jeryu/deploy-env/<release>
  --domain:  git.neverhuman.org
  --host:    atomicsoul
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --release)
      shift
      release="${1:-}"
      ;;
    --out-dir)
      shift
      out_dir="${1:-}"
      ;;
    --force)
      force=1
      ;;
    --domain)
      shift
      domain="${1:-}"
      ;;
    --host)
      shift
      host="${1:-}"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'make-production-env: unknown arg: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

need() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'make-production-env: missing required command: %s\n' "$1" >&2
    exit 1
  }
}

need openssl
need sha256sum

commit="$(git rev-parse --verify HEAD 2>/dev/null || printf 'nogit')"
if [[ -z "${release}" ]]; then
  stamp="$(date -u +%Y%m%dT%H%M%SZ)"
  release="prod-${stamp}-${commit:0:12}"
fi

if [[ ! "${release}" =~ ^[A-Za-z0-9._-]+$ ]]; then
  printf 'make-production-env: release must contain only letters, digits, dot, underscore, and dash: %s\n' "${release}" >&2
  exit 2
fi

if [[ -z "${out_dir}" ]]; then
  out_dir="${HOME}/.jeryu/deploy-env/${release}"
fi

if [[ -e "${out_dir}" && "${force}" != "1" ]]; then
  printf 'make-production-env: refusing to overwrite existing directory: %s\n' "${out_dir}" >&2
  printf 'make-production-env: pass --force to replace it\n' >&2
  exit 1
fi

rm -rf "${out_dir}"
install -d -m 0700 "${out_dir}"
out_dir_abs="$(cd "${out_dir}" && pwd)"

deploy_signer="${out_dir_abs}/signing-key.pem"
public_key="${out_dir_abs}/signing-key.pub.pem"
env_file="${out_dir_abs}/production.env"
public_env="${out_dir_abs}/PUBLIC.env"
readme="${out_dir_abs}/README.txt"

admin_password="$(openssl rand -hex 36)"
signrail_seed="$(openssl rand -hex 32)"

openssl genpkey -algorithm Ed25519 -out "${deploy_signer}" >/dev/null 2>&1
openssl pkey -in "${deploy_signer}" -pubout -out "${public_key}" >/dev/null 2>&1
chmod 0600 "${deploy_signer}"
chmod 0644 "${public_key}"

pubkey_sha="$(sha256sum "${public_key}" | awk '{print $1}')"
release_dir="${release_root%/}/${release}"

write_export() {
  local key="$1" value="$2"
  printf 'export %s=%q\n' "${key}" "${value}"
}

umask 077
{
  printf '# Generated by ops/deploy/make-production-env.sh. Do not commit.\n'
  printf '# Release material is intentionally per-release; regenerate for every production release.\n'
  write_export JERYU_DEPLOY_RELEASE "${release}"
  write_export JERYU_RELEASE_TAG "${release}"
  write_export JERYU_RELEASE_COMMIT "${commit}"
  write_export JERYU_PRODUCTION_DOMAIN "${domain}"
  write_export JERYU_PRODUCTION_ORIGIN "https://${domain}"
  write_export JERYU_ATOMICSOUL_HOST "${host}"
  write_export JERYU_ATOMICSOUL_RELEASE_ROOT "${release_root}"
  write_export JERYU_ATOMICSOUL_RELEASE_DIR "${release_dir}"
  write_export JERYU_SERVE_BIND "${bind}"
  write_export JERYU_DATA_DIR "${data_dir}"
  write_export JERYU_SPA_DIR "${spa_dir}"
  write_export JERYU_SPLIT_MANIFEST "${split_manifest}"
  write_export JERYU_BOOTSTRAP_ADMIN_PASSWORD "${admin_password}"
  write_export JERYU_SIGNRAIL_ED25519_SEED "${signrail_seed}"
  write_export JERYU_DEPLOY_SIGNING_KEY "${deploy_signer}"
  write_export JERYU_DEPLOY_SIGNING_PUBKEY "${public_key}"
  write_export JERYU_DEPLOY_SIGNING_PUBKEY_SHA256 "${pubkey_sha}"
  write_export SIGNRAIL_ROLLBACK_TARGET "${SIGNRAIL_ROLLBACK_TARGET:-}"
} >"${env_file}"
chmod 0600 "${env_file}"

{
  printf '# Nonsecret metadata for %s.\n' "${release}"
  write_export JERYU_DEPLOY_RELEASE "${release}"
  write_export JERYU_RELEASE_COMMIT "${commit}"
  write_export JERYU_PRODUCTION_DOMAIN "${domain}"
  write_export JERYU_ATOMICSOUL_HOST "${host}"
  write_export JERYU_ATOMICSOUL_RELEASE_DIR "${release_dir}"
  write_export JERYU_DEPLOY_SIGNING_PUBKEY_SHA256 "${pubkey_sha}"
} >"${public_env}"
chmod 0644 "${public_env}"

cat >"${readme}" <<EOF
Jeryu production env material for ${release}

Secret file:
  ${env_file}

Use it with:
  set -a
  . "${env_file}"
  set +a

Then build/sign the release bundle and push it:
  SIGNRAIL_ROLLBACK_TARGET=<previous-release> bash ops/ci/artifact_support.sh
  bash ops/ci/release.sh
  ops/deploy/sign-and-push-atomicsoul.sh --env "${env_file}"

The admin password and signing keys in production.env are per-release secrets.
Keep ${out_dir_abs} local, encrypted, or destroy it after the release is fully
audited and rollback material is archived.
EOF
chmod 0644 "${readme}"

printf '[make-production-env] wrote secret env: %s\n' "${env_file}"
printf '[make-production-env] wrote public metadata: %s\n' "${public_env}"
printf '[make-production-env] public signing key sha256: %s\n' "${pubkey_sha}"
